CREATE GLOBAL TEMPORARY TABLE "SYSDBA"."##HISTOGRAMS_TABLE"
(
"OWNER" VARCHAR(128),
"TABLE_NAME" VARCHAR(128),
"COLUMN_NAME" VARCHAR(128),
"HISTOGRAM" VARCHAR(15),
"ENDPOINT_VALUE" VARCHAR(128),
"ENDPOINT_HEIGHT" BIGINT,
"ENDPOINT_KEYHEIGHT" BIGINT,
"ENDPOINT_DISTINCT" BIGINT)
ON COMMIT DELETE ROWS STORAGE(ON TEMP);

CREATE GLOBAL TEMPORARY TABLE "SYSDBA"."##PLAN_TABLE"
(
"PLAN_ID" INT,
"PLAN_NAME" VARCHAR(128),
"CREATE_TIME" DATETIME(6),
"LEVEL_ID" INT,
"OPERATION" VARCHAR(30),
"TAB_NAME" VARCHAR(128),
"IDX_NAME" VARCHAR(128),
"SCAN_TYPE" VARCHAR(20),
"SCAN_RANGE" VARCHAR(128),
"ROW_NUMS" BIGINT,
"BYTES" INT,
"COST" BIGINT,
"CPU_COST" BIGINT,
"IO_COST" BIGINT,
"FILTER" VARCHAR(1000),
"JOIN_COND" VARCHAR(1000),
"ADVICE_INFO" VARCHAR(1000),
"PSTART" INT,
"PSTOP" INT)
ON COMMIT PRESERVE ROWS STORAGE(ON TEMP);

CREATE TABLE "SYSDBA"."CIM_ATTACHMENT"
(
"ID" VARCHAR(50) NOT NULL,
"FILENAME" VARCHAR(50),
"OLDNAME" VARCHAR(200),
"FILEPATH" VARCHAR(200),
"USERID" VARCHAR(50),
"CREATETIME" DATETIME(6),
"KEY" VARCHAR(50),
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYSDBA"."CIM_ATTACHMENT" IS '附件信息表';
COMMENT ON COLUMN "SYSDBA"."CIM_ATTACHMENT"."ID" IS '主键';
COMMENT ON COLUMN "SYSDBA"."CIM_ATTACHMENT"."FILENAME" IS '文件存储名称';
COMMENT ON COLUMN "SYSDBA"."CIM_ATTACHMENT"."OLDNAME" IS '文件名称';
COMMENT ON COLUMN "SYSDBA"."CIM_ATTACHMENT"."FILEPATH" IS '存储路径';
COMMENT ON COLUMN "SYSDBA"."CIM_ATTACHMENT"."USERID" IS '上传人';
COMMENT ON COLUMN "SYSDBA"."CIM_ATTACHMENT"."CREATETIME" IS '上传时间';
COMMENT ON COLUMN "SYSDBA"."CIM_ATTACHMENT"."KEY" IS '哈希码';


CREATE TABLE "SYSDBA"."CIM_PROJECT_MODEL"
(
"ID" VARCHAR(50) NOT NULL,
"PROJECTCODE" VARCHAR(65),
"LAYERCODE" VARCHAR(16),
"URL" VARCHAR(5000),
"USERID" VARCHAR(65),
"CREATETIME" DATETIME(6),
"SUBCODENAME" VARCHAR(65),
"IMAGEDATE" DATE,
"BUILDINGCODE" VARCHAR(50),
"SPECIALITY" VARCHAR(50),
"VERSION" NUMBER(22,6),
"ATTCHMENTID" VARCHAR(50),
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYSDBA"."CIM_PROJECT_MODEL" IS '模型索引表';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."ID" IS '主键';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."PROJECTCODE" IS '工程编码';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."LAYERCODE" IS '图层编码（对应模型类别）	LayerCode	varchar	16			设计模型、场布模型、竣工模型、倾斜摄影、';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."URL" IS 'config配置信息';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."USERID" IS '用户ID';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."SUBCODENAME" IS '子类编码名（如场布模型名，）';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."IMAGEDATE" IS '拍摄日期';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."BUILDINGCODE" IS '单体编码';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."SPECIALITY" IS '所属专业';
COMMENT ON COLUMN "SYSDBA"."CIM_PROJECT_MODEL"."VERSION" IS '版本';


CREATE TABLE "SYSDBA"."USERINFO"
(
"ID" NUMBER(22,6) NOT NULL,
"NAME" VARCHAR(50),
"AGE" NUMBER(22,6),
"MONEY" NUMBER(22,6),
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

